source 'http://rubygems.org'

gem 'acts_as_list'
gem 'amazon-ecs'
gem 'calendar_date_select', :git => 'http://github.com/paneq/calendar_date_select.git', :branch => 'rails3test'
gem 'dynamic_form'
gem 'fb_graph'
gem 'haml'
gem 'httparty'
gem 'json'
gem 'mysql2'
gem 'nokogiri'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'prototype_legacy_helper', '0.0.0', :git => 'git://github.com/rails/prototype_legacy_helper.git'
gem 'rails'
gem 'sass'
gem 'wikipedia-client'
gem 'will_paginate', "~> 3.0.pre2"