source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'fb_graph'
gem 'haml'
gem 'hpricot', '0.8.1'
gem 'amazon-ecs'
gem 'will_paginate'
gem 'dynamic_form'
gem 'omniauth'
gem 'calendar_date_select', :git => 'http://github.com/paneq/calendar_date_select.git', :branch => 'rails3test'
gem 'prototype_legacy_helper', '0.0.0', :git => 'git://github.com/rails/prototype_legacy_helper.git'
gem 'wikipedia-client'