
development:
  secret_key_base: <%= Secret['rails_secret_key_base'] %>
 
test:
  secret_key_base: <%= Secret['rails_secret_key_base'] %>
 
production:
  secret_key_base: <%= Secret['rails_secret_key_base'] %>

