#!/usr/bin/env bash
export RAILS_ENV=production
cd /home/ubuntu/gamerankr
git checkout .
git pull
/home/ubuntu/.rbenv/shims/bundle
/home/ubuntu/.rbenv/shims/bundle exec rails assets:precompile
sudo systemctl restart puma